#!/usr/bin/env bash
# Transfers files and accepts 4 parameters
# First run ssh ubuntu@54.157.190.122 -i ~/.ssh/school 'ls~/'
# after runnning

if [ $# -lt 3]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi
