#!/usr/bin/env bash
# install nginx on web server,
# set Nginx to listen to port 80
# Query Nginx at root with GET request
# curl http://54.157.190.122/
# curl http://54.157.190.122/

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
