#!/usr/bin/env bash

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Configure Nginx
sudo bash -c "cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        echo \"Hello World!\";
    }
}
EOF"

# Restart Nginx
sudo service nginx restart

