#!/usr/bin/env bash

# Update package index
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Configure Nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
# Restart Nginx
sudo service nginx restart

