#!/usr/bin/env bash
# Bash script that displays 1 to 100
# display FizzBuzz if a multiple of 3 & 5
# displays Fizz if a multiple of 3
# displays Buzz if a multiple of 5
# else displays number
i=1
while [ $i -le 100 ]
do
	if (( i % 3 == 0 )) && (( i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then	
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
