#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# Displays username, user id, home directory path for the user
while read line
do
	user=$(echo "$line" | cut -d: -f1)
	uid=$(echo "$line" | cut -d: -f3)
	home=$(echo "$line" | cut -d: -f6)
	echo "$user:$uid:$home"
done < /etc/passwd
