#!/usr/bin/env bash
# Bash script uses if and while to print Best School
# except the 9th iteration it prints Hi
i=0
while [ $i -lt 10 ]
do
	if [ $i = 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
