#!/usr/bin/env bash
# Bash script that loops 1 to 10 using while loop and if-elif-else
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best school"
	fi
	((i +=1))
done

