#!/usr/bin/env bash
# Bash script that loops 1 to 10 using while loop and if-elif-else
i=0
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best school"
	fi
	((i++))
done

