#!/usr/bin/env bash
# Bash scripts displays from 1 to 20
# displays 4 and then bad luck from China
# displays 9 and then bad luck from Japan
# displays 17 and then bad lack from Italy
i=1
while [ $i -le 20 ]
do
case $i in
"5" )
echo "bad luck from China"
;;
"10" )
echo "bad luck from Japan"
;;
"18" )
echo "bad luck from Italy"
;;
esac
echo $i
((i++))
done

