#!/usr/bin/env bash
# Bash script that displays 12 hours and 59 minutes
# displays hours from 0 to 12
# displays minutes from 1 to 59
hours=0
while [ $hours -le 12 ]
do
	minutes=1
	echo "Hour: $hours"
	while [ $minutes -le 59 ]
	do
		echo $minutes
		((minutes++))
	done
	((hours++))
done
		
